### PR TITLE
More Performance improvements and Bug fixes!

### PR DESCRIPTION
**Pull request by ItsEeleeya**
Added a new command exception type, Permission Exception and its also configurable through the Messages config
*UnTested* Locator and RTP Threads now interrupt the thread and return after they done executing
Added InventoryCommand, Still need to make a custom Container or Inventory
Some small lang file changes
Signs now accept formatting codes! Required permission: `kiloessentials.sign.color`
Fixed `TabCompletions::usableCommands` so it doesn't show the arguments (e.g: cmd toast) anymore
Changed the second argument of the UsageCommand to a `greedyString()` from `word()`
Removed WarpManager from the OnReload event
Fixed one small issue with the ItemLoreCommand
Updated version to `1.6.9`

### CODE REVIEW

**Comment by MarcusElg** [comment]
Nice work with the inventory command sign formatting.

Are you sure the usuage command works? Because the reason I made it a word is that it completely ignored everything except thr fort word anyways.

**Comment by ItsEeleeya** [comment]
> 
> 
> Nice work with the inventory command sign formatting.
> 
> Are you sure the usuage command works? Because the reason I made it a word is that it completely ignored everything except thr fort word anyways.

It does the same thing as before
you can try `/usage home woo`  and it will show you the correct arguments

**Review by MarcusElg — APPROVED** [review]

**Comment by MarcusElg** [comment]
I'll test it when it's merged

**Comment by ItsEeleeya** [comment]
> 
> 
> Nice work with the inventory command sign formatting.
> 
> Are you sure the usuage command works? Because the reason I made it a word is that it completely ignored everything except thr fort word anyways.

It does the same thing as before
you can try `/usage home woo`  and it will show you the correct arguments

**Pull request merged**
